-- MySQL Script generated by MySQL Workbench
-- mer. 11 janv. 2023 15:52:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema production
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema production
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `production` ;
USE `production` ;

-- -----------------------------------------------------
-- Table `production`.`labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `production`.`labels` (
  `code_label` INT NOT NULL,
  `nom_label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code_label`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `production`.`disques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `production`.`disques` (
  `code_disque` INT NOT NULL,
  `titre` VARCHAR(45) NOT NULL,
  `labels_code_label` INT NOT NULL,
  PRIMARY KEY (`code_disque`),
  INDEX `fk_disques_labels1_idx` (`labels_code_label` ASC) VISIBLE,
  CONSTRAINT `fk_disques_labels1`
    FOREIGN KEY (`labels_code_label`)
    REFERENCES `production`.`labels` (`code_label`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `production`.`artistes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `production`.`artistes` (
  `code_artiste` INT NOT NULL,
  `nom_artiste` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code_artiste`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `production`.`y`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `production`.`y` (
  `participent`  NULL);


-- -----------------------------------------------------
-- Table `production`.`assos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `production`.`assos` (
  `disques_code_disque` INT NOT NULL,
  `artistes_code_artiste` INT NOT NULL,
  PRIMARY KEY (`disques_code_disque`, `artistes_code_artiste`),
  INDEX `fk_disques_has_artistes_artistes1_idx` (`artistes_code_artiste` ASC) VISIBLE,
  INDEX `fk_disques_has_artistes_disques1_idx` (`disques_code_disque` ASC) VISIBLE,
  CONSTRAINT `fk_disques_has_artistes_disques1`
    FOREIGN KEY (`disques_code_disque`)
    REFERENCES `production`.`disques` (`code_disque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disques_has_artistes_artistes1`
    FOREIGN KEY (`artistes_code_artiste`)
    REFERENCES `production`.`artistes` (`code_artiste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
