-- MySQL Script generated by MySQL Workbench
-- mer. 11 janv. 2023 15:41:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Labels` (
  `idLabels` INT NOT NULL AUTO_INCREMENT,
  `nom label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLabels`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disques` (
  `idDisques` INT NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(45) NOT NULL,
  `année` DATE NULL,
  `Labels_idLabels` INT NOT NULL,
  `Labels_idLabels1` INT NOT NULL,
  PRIMARY KEY (`idDisques`, `Labels_idLabels1`),
  INDEX `fk_Disques_Labels1_idx` (`Labels_idLabels1` ASC) VISIBLE,
  CONSTRAINT `fk_Disques_Labels1`
    FOREIGN KEY (`Labels_idLabels1`)
    REFERENCES `mydb`.`Labels` (`idLabels`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artiste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Artiste` (
  `idArtiste` INT NOT NULL AUTO_INCREMENT,
  `nom artiste` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idArtiste`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`participe` (
  `idDisques` INT NOT NULL,
  `idArtiste` INT NOT NULL,
  PRIMARY KEY (`idDisques`, `idArtiste`),
  INDEX `fk_Disques_has_Artiste_Artiste1_idx` (`idArtiste` ASC) VISIBLE,
  INDEX `fk_Disques_has_Artiste_Disques_idx` (`idDisques` ASC) VISIBLE,
  CONSTRAINT `fk_Disques_has_Artiste_Disques`
    FOREIGN KEY (`idDisques`)
    REFERENCES `mydb`.`Disques` (`idDisques`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disques_has_Artiste_Artiste1`
    FOREIGN KEY (`idArtiste`)
    REFERENCES `mydb`.`Artiste` (`idArtiste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
